services:
  app:
    build:
      context: .
      dockerfile: docker/php83/Dockerfile
    container_name: ci4_app
    volumes:
      - ./src:/var/www
    networks:
      - ci4

  web:
    image: httpd:2.4
    container_name: ci4_web
    depends_on:
      - app
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./docker/apache/vhost.conf:/usr/local/apache2/conf/extra/vhost.conf

    command: >
      sh -c "
      sed -i 's/#LoadModule rewrite_module/LoadModule rewrite_module/' /usr/local/apache2/conf/httpd.conf &&
      sed -i 's/#LoadModule proxy_module/LoadModule proxy_module/' /usr/local/apache2/conf/httpd.conf &&
      sed -i 's/#LoadModule proxy_fcgi_module/LoadModule proxy_fcgi_module/' /usr/local/apache2/conf/httpd.conf &&
      echo 'Include conf/extra/vhost.conf' >> /usr/local/apache2/conf/httpd.conf &&
      httpd-foreground
      "

    networks:
      - ci4
      # - app
      # - db

  db:
    image: mysql:8
    container_name: ci4_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ci4
      MYSQL_USER: ci4user
      MYSQL_PASSWORD: ci4pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - ci4

# STO ESTAVA FALTANDO 
networks:
  ci4:
    driver: bridge

volumes:
  db_data:
